name: dart_learning
description: Dart学习示例项目，演示不同类型的库的使用

# 指定Dart SDK版本范围
environment:
  sdk: '>=2.12.0 <3.0.0'

# 项目依赖
dependencies:
  # 添加http包作为依赖
  http: ^0.13.4
  
  # 可以添加更多依赖
  # path: ^1.8.0
  # intl: ^0.17.0

# 开发环境依赖（不会包含在生产环境）
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
